apiVersion: v1 
kind: Service 
metadata: 
  name: udagram-frontend
  labels: 
    app: udagram-frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-frontend-svc
spec: 
  ports: 
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector: 
    app: udagram-frontend
  sessionAffinity: None
  type: ClusterIP