apiVersion: v1 
kind: Service 
metadata: 
  name: udagram-reverse-proxy
  labels: 
    app: udagram-reverse-proxy
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-reverse-proxy-svc
spec: 
  ports: 
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector: 
    app: udagram-reverse-proxy
  sessionAffinity: None
  type: ClusterIP