apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: udagram-api-user
  labels: 
    app: udagram-api-user 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: udagram-api-user
  template: 
    metadata: 
      labels: 
        app: udagram-api-user
    spec: 
      containers: 
      - name: udagram-api-user
        image: bezag/udagram-api-user
        ports: 
        - containerPort: 8080
        env:
        - name: POSTGRES_USERS_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: POSTGRES_USERS_HOST 
        - name: POSTGRES_USERS_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: POSTGRES_USERS_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: AWS_REGION     
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-config-map          # The ConfigMap this value comes from.
              key: JWT_SECRET
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret          # The ConfigMap this value comes from.
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret          # The ConfigMap this value comes from.
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: dockercred
